flexibilities: [EWH, BEV, EWH+BEV, BEV+V2G, EWH+BEV+V2G]
 
year: "2050"
historical_year: "2012"
demand: 522.e+6 # 344TWh 2030, 428TWh 2040, 522TWh 2050
                # IRP_Update_Assumptions_1904.pdf

csp: false

masks: ['corridors', 'redz']

 # Gives us ball-park the available areas the IWES study reports
landusetype_percent:
  wind:
    - [[7, 8, 9, 41], 100]
    # - [[5, 6], 50]
    # - [[11, 12, 14, 15], 10]
  solar:
    - [[7, 8, 9, 41], 100]
    # - [[11, 12, 14, 15], 50]
    # - [[46, 47, 51, 56, 64, 68, 72], 10]

capacity_per_sqm:
  wind: 5   # half of the IWES study: 10
  solar: 15 # half of the IWES study: 33

hydro_inflow:
  countries: ['ZA', 'MZ']
  cutout: 'za-mz-2012'

extendable_carriers:
  Generator: ['OCGT']
  StorageUnit: ['Battery', 'CAES']

max_hours:
  Battery: 3
  CAES: 10

costs:
  EUR_to_ZAR: 15.63
  # costs come from data/internal/IRP2016_Inputs_Technology-Costs (PUBLISHED).xlsx
  sheetname: "IRP-Apr2016" # "CSIR-Apr2016"
  discountrate: 0.08
  # except for lines which are specified here
  line:
    transport: false
    overnight: 6000 # R/MWkm 400 * 15.63
    s_nom_factor: 0.7
    length_factor: 1.25
    lifetime: 40
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: # 
    PV: 0.01
    Wind: 0.015

transport:
  # Table 18 in 20170331CSIR_EC_DOE p. 48 (64)
  energy_total: 26.7e+6 # 24 2030, 25.2 2040, 26.7 2050
  # efficiency_gain: 3.5 # Explanation
  availability_max: 0.95
  availability_mean: 0.8
  total_cars: 8.9e+6 # 8.0 2030, 8.4 2040, 8.9 2050
  car_battery_p_nom: 0.011 # 11kW 3-phase charger
  car_battery_e_nom: 0.05  # 50kWh battery
  # http://www.zeit.de/mobilitaet/2014-10/auto-fahrzeug-bestand
  standing_loss: 8.33e-5 # Buddischak
  efficiency: 0.9 # "

  # cars_per_person: 0.6

solving:
  tmpdir: /tmp
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    formulation: 'kirchhoff'
  solver:
    name: "gurobi"
    threads: 4
    method: 2
    crossover: 0 # -1 (Choose freely)
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
