scenario:
  mask: ['corridors', 'redz']
  sectors: [E, E+BEV] #, E+BEV, E+BEV+V2G]
 
year: "2050"
historical_year: "2012"
demand: 522.e+6 # 344TWh 2030, 428TWh 2040, 522TWh 2050
                # IRP_Update_Assumptions_1904.pdf

csp: false

masks: ['corridors', 'redz']

 # Gives us ball-park the available areas the IWES study reports
landusetype_percent:
  wind:
    - [[7, 8, 9, 41], 80]
    # - [[5, 6], 50]
    # - [[11, 12, 14, 15], 10]
  solar:
    - [[7, 8, 9, 41], 80]
    # - [[11, 12, 14, 15], 50]
    # - [[46, 47, 51, 56, 64, 68, 72], 10]

capacity_per_sqm:
  wind: 5   # half of 10 (IWES)
  solar: 15 # "half" of 33 (IWES)

hydro_inflow:
  countries: ['ZA', 'MZ']
  cutout: 'za-mz-2012'

extendable_carriers:
  Generator: ['OCGT']
  StorageUnit: ['Battery', 'CAES']

max_hours:
  Battery: 3
  CAES: 10

costs:
  EUR_to_ZAR: 15.63
  # costs come from data/internal/IRP2016_Inputs_Technology-Costs (PUBLISHED).xlsx
  sheetname: "IRP2016-Apr2016" # "CSIR-Apr2016"
  discountrate: 0.08
  # except for lines which are specified here
  line:
    transport: false
    overnight: 6000 # R/MWkm 400 * 15.63
    s_nom_factor: 0.7
    length_factor: 1.25
    lifetime: 40
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: # 
    PV: 0.01
    Wind: 0.015

transport:
  # Table 18 in 20170331CSIR_EC_DOE p. 48 (64)
  energy_total: 26.7e+6 # 24 2030, 25.2 2040, 26.7 2050
  # efficiency_gain: 3.5 # Explanation
  availability_max: 0.95
  availability_mean: 0.8
  total_cars: 8.9e+6 # 8.0 2030, 8.4 2040, 8.9 2050
  car_battery_p_nom: 0.011 # 11kW 3-phase charger
  car_battery_e_nom: 0.05  # 50kWh battery
  # http://www.zeit.de/mobilitaet/2014-10/auto-fahrzeug-bestand
  standing_loss: 8.33e-5 # Buddischak
  efficiency: 0.9 # "

  # cars_per_person: 0.6

solving:
  tmpdir: /tmp
  options:
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    formulation: 'kirchhoff'
  solver:
    name: "gurobi"
    threads: 4
    method: 2
    crossover: 0 # -1 (Choose freely)
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6

plotting:
  vre_techs: ["Wind", "PV"]
  conv_techs: ["OCGT", "Diesel", "Coal"]
  storage_techs: ["PHS", "hydro", "H2", "battery"]
  store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load", "heat load", "Li ion load"]
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    onwind: "b"
    onshore wind: "b"
    offwind: "c"
    offshore wind: "c"
    hydro: "g"
    ror: "g"
    solar: "y"
    OCGT: "brown"
    OCGT marginal: "sandybrown"
    OCGT-heat: "orange"
    central gas boiler: "orange"
    gas boiler: "orange"
    gas boilers: "orange"
    gas boiler marginal: "orange"
    gas: "brown"
    lines: "k"
    transmission lines: "k"
    H2: "m"
    hydrogen storage: "m"
    battery: "slategray"
    battery storage: "slategray"
    Nuclear: "r"
    Nuclear marginal: "r"
    Coal: "k"
    Coal marginal: "k"
    Lignite: "grey"
    Lignite marginal: "grey"
    CCGT: "orange"
    CCGT marginal: "orange"
    heat pumps: "green"
    heat pump: "green"
    central heat pump: "green"
    resistive heater: "pink"
    central resistive heater: "pink"
    Sabatier: "turquoise"
    water tanks: "w"
    CHP: "r"
    CHP heat: "r"
    CHP electric: "r"
    central CHP heat: "r"
    central CHP electric: "r"
    PHS: "g"
    Ambient: "k"
    Electric load: "b"
    Heat load: "r"
    Transport load: "grey"
    heat: "r"
    Li ion: "grey"
    district heating: "#CC4E5C"
  nice_names:
    offwind: "offshore wind"
    onwind: "onshore wind"
    OCGT: "gas"
    H2: "hydrogen storage"
    battery: "battery storage"
    OCGT marginal: "gas (marginal)"
    lines: "transmission lines"
    ror: "run of river"
  nice_names_n:
    offwind: "offshore\nwind"
    onwind: "onshore\nwind"
    OCGT: "gas"
    H2: "Hydrogen\nstorage"
    OCGT marginal: "gas (marginal)"
    lines: "transmission\nlines"
    ror: "run of river"

# plotting:
#   vre_techs: ["windon", "windoff"]
#   conv_techs: ["OCGT", "gas boiler"]
#   storage_techs: ["PHS", "hydro", "H2", "battery"]
#   store_techs: ["Li ion", "water tanks"]
#   load_carriers: ["AC load", "heat load", "Li ion load"]
#   heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
#                "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
#                "central CHP electric", "central gas boiler"]
#   heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
#   tech_colors:
#     onwind: "b"
#     onshore wind: "b"
#     offwind: "c"
#     offshore wind: "c"
#     hydro: "g"
#     ror: "g"
#     solar: "y"
#     OCGT: "brown"
#     OCGT marginal: "sandybrown"
#     OCGT-heat: "orange"
#     central gas boiler: "orange"
#     gas boiler: "orange"
#     gas boilers: "orange"
#     gas boiler marginal: "orange"
#     gas: "brown"
#     lines: "k"
#     transmission lines: "k"
#     H2: "m"
#     hydrogen storage: "m"
#     battery: "slategray"
#     battery storage: "slategray"
#     Nuclear: "r"
#     Nuclear marginal: "r"
#     Coal: "k"
#     Coal marginal: "k"
#     Lignite: "grey"
#     Lignite marginal: "grey"
#     CCGT: "orange"
#     CCGT marginal: "orange"
#     heat pumps: "green"
#     heat pump: "green"
#     central heat pump: "green"
#     resistive heater: "pink"
#     central resistive heater: "pink"
#     Sabatier: "turquoise"
#     water tanks: "w"
#     CHP: "r"
#     CHP heat: "r"
#     CHP electric: "r"
#     central CHP heat: "r"
#     central CHP electric: "r"
#     PHS: "g"
#     Ambient: "k"
#     Electric load: "b"
#     Heat load: "r"
#     Transport load: "grey"
#     heat: "r"
#     Li ion: "grey"
#     district heating: "#CC4E5C"
#   nice_names:
#     offwind: "offshore wind"
#     onwind: "onshore wind"
#     OCGT: "gas"
#     H2: "hydrogen storage"
#     battery: "battery storage"
#     OCGT marginal: "gas (marginal)"
#     lines: "transmission lines"
#     ror: "run of river"
#   nice_names_n:
#     offwind: "offshore\nwind"
#     onwind: "onshore\nwind"
#     OCGT: "gas"
#     H2: "Hydrogen\nstorage"
#     OCGT marginal: "gas (marginal)"
#     lines: "transmission\nlines"
#     ror: "run of river"
